### ISSUE TITLE
calico.sh usage warning is wrong

### ISSUE THREAD

**Issue by plwhite** [brooklyncentral/clocker#106]
This is rather a trivial issue, but the calico.sh script contains a usage statement that says "Usage: clocker.sh...".

I'd just submit a patch, but given that clocker.sh and calico.sh are exactly the same except for one file name, it occurred to me to ask if instead it would be better to have just a single clocker.sh, and present the networking type as an argument to it? That seems more intuitive to me, since calico.sh is an odd command to run to start up clocker!

**Comment by grkvlt** [comment]
@plwhite you're probably right. I've been thinking about this for a while, and I'm going to change the way the scripts work to fix this.

**Comment by grkvlt** [comment]
Updated script usage with network argument
