### ISSUE TITLE
Incorrect logo in "Clocker with Weave" 

### ISSUE THREAD

**Issue by plwhite** [brooklyncentral/clocker#107]
If you go to the Brooklyn web console, you can create "Local Clocker" which has a Docker logo; "Clocker with Calico" which has a Calico logo; and "Clocker with Weave" which has the Docker logo again. That last probably should have the Weave logo (although I confess that I have been unable to find a weave logo that is definitively the right one to use!).

**Comment by grkvlt** [comment]
@plwhite I didn't know what logo to use either!

**Comment by grkvlt** [comment]
Have changed to use the @weaveworks Twitter avatar
