### ISSUE TITLE
Utilise spotify docker client

### ISSUE THREAD

**Issue by csabapalfi** [brooklyncentral/clocker#119]
Spotify released a Java docker-client some time ago now: https://github.com/spotify/docker-client

I think it would be awesome if we can switch to that instead of using the shell to execute docker commands.

It's just an idea at this point but I have high hopes for that making our lives simpler.

**Comment by andreaturli** [comment]
@csabapalfi, do you think it is better to add an extra dep instead of using https://github.com/jclouds/jclouds-labs/tree/master/docker as we did elsewhere in the project?
Can you specify what features are provided by spotify/docker-client that you'd like to use and are not offered by jclouds-docker ? Thanks!

**Comment by csabapalfi** [comment]
@andreaturli Thanks for the quick reply. One limitation with jclouds docker is that we need SSHable containers.

Lots of people moved away from running containers with sshd when first nsenter then docker exec became available. In a lot of cases a third-party image won't have sshd and trying to install it on top of these images can result in issues (e.g different distros, different default CMDs and/or service management within containers).

I guess it probably needs further investigation and my limited experience with jclouds is not helping but I'm learning :) Happy to look into this a bit more later on.

**Comment by grkvlt** [comment]
@csabapalfi @andreaturli Actually, we don't *need* SSH-able containers for jclouds to work - I turned off some of the SSH-able access checks in jclouds, when creating a compute node, and we could do more there. And other things we do to the container are effected by running `docker` commands on the host. I think the benefits of re-using the Brooklyn jclouds driver and location infrastructure outweigh the work in adding a new client. If we can use jclouds to create a container, then `docker exec` and `docker attach` to run commands there, that seems good to me.

**Comment by csabapalfi** [comment]
Thanks for the clarification @grkvlt!

Happy to just stick to jclouds then. Closing this now.
