### ISSUE TITLE
NoSuchMethodError DockerTemplateOptions.hostname(Ljava/lang/String;)

### ISSUE THREAD

**Issue by sjcorbett** [brooklyncentral/clocker#128]
Cloned and built Clocker on a VM in Softlayer Amsterdam and run, again in Amsterdam.

Clocker deploys fine but all attempts to provision containers fail immediately with this exception: 
```
Caused by: java.lang.NoSuchMethodError: org.jclouds.docker.compute.options.DockerTemplateOptions.hostname(Ljava/lang/String;)Lorg/jclouds/docker/compute/options/DockerTemplateOptions;
	at brooklyn.entity.container.docker.DockerContainerImpl.getDockerTemplateOptions(DockerContainerImpl.java:271)
	at brooklyn.entity.container.docker.DockerContainerImpl.createLocation(DockerContainerImpl.java:421)
	at brooklyn.entity.container.docker.DockerContainerImpl.start(DockerContainerImpl.java:570)
```

Tried experimenting with the Groovy console:
```
Class.forName("org.jclouds.docker.compute.options.DockerTemplateOptions").getMethod("hostname", String.class)

public org.jclouds.docker.compute.options.DockerTemplateOptions org.jclouds.docker.compute.options.DockerTemplateOptions.hostname(java.lang.String)
```

DockerTemplateOptions exists in `brooklyn-clocker-docker-0.9.0-SNAPSHOT.jar` and `docker-1.9.0.jar`. Both are on the server's classpath.

javap and grepping for hostname  on both:
```
sam@br-vnc5-sam-opil-emp-lv0x-a18:~/git/clocker/examples/target/brooklyn-clocker-dist/brooklyn-clocker/lib/brooklyn$ javap -classpath ./brooklyn-clocker-docker-0.9.0-SNAPSHOT.jar org.jclouds.docker.compute.options.DockerTemplateOptions | grep -i hostname
  protected com.google.common.base.Optional<java.lang.String> hostname;
  public org.jclouds.docker.compute.options.DockerTemplateOptions hostname(java.lang.String);
  public com.google.common.base.Optional<java.lang.String> getHostname();
sam@br-vnc5-sam-opil-emp-lv0x-a18:~/git/clocker/examples/target/brooklyn-clocker-dist/brooklyn-clocker/lib/brooklyn$ javap -classpath docker-1.9.0.jar org.jclouds.docker.compute.options.DockerTemplateOptions | grep -i hostname
  protected com.google.common.base.Optional<java.lang.String> hostname;
  public org.jclouds.compute.options.TemplateOptions hostname(java.lang.String);
  public com.google.common.base.Optional<java.lang.String> getHostname();
```
I'm struggling to work this one out.

**Comment by sjcorbett** [comment]
Candidate suggestion is that docker-1.9.0.jar is being picked up.

The `org.jclouds.docker.compute.options.DockerTemplateOptions` class in there returns `org.jclouds.compute.options.TemplateOptions`, not `org.jclouds.docker.compute.options.DockerTemplateOptions`, thus error.

The docker module pom excludes `${jclouds.groupId}.labs:docker`. Has it been included accidentally?

**Comment by neykov** [comment]
This exact problem was patched in clocker in https://github.com/brooklyncentral/clocker/commit/3580bb4c9a10966119276b50f97877b76442dd3b and fixed upstream, probably there's still an old version somewhere on the classpath?

**Comment by sjcorbett** [comment]
It's a brand new checkout of master.

**Comment by sjcorbett** [comment]
@neykov Sorry, was a bit tired last night. You're right, there's an old version on the classpath still.

**Comment by sjcorbett** [comment]
I deleted `DockerTemplateOptions` from `docker-1.9.0.jar`, leaving the version in `brooklyn-clocker-docker-0.9.0-SNAPSHOT.jar`. Redeployed and had success.
