### ISSUE TITLE
Container creation fails if Clocker server and Docker hosts running in same AWS region

### ISSUE THREAD

**Issue by aledsage** [brooklyncentral/clocker#134]
We deployed a clocker instance to a VM in AWS us-west-1, and then from that we deployed a "Clocker with Weave" to the same AWS region. This deployed successfully.

However, whenever attempting to deploy an app to the new docker-location, it failed to create any containers.

The reason is that the auto-generated security group opens port 2376 just to the public IP of the Clocker server. However, when connecting from within the same region it uses an internal IP address. Therefore the Clocker server cannot reach port 2376 on the Docker hosts (as confirmed using `telnet <hostname> 2376` from the Clocker server).

The workaround is to deploy your "Clocker with Weave" to a different AWS region.

**Comment by grkvlt** [comment]
Fix is probably to add the private IP details to the security group as well.
