### ISSUE TITLE
Weave Docker infrastructure setup fails when Softlayer VMs get created in different VLANs

### ISSUE THREAD

**Issue by csabapalfi** [brooklyncentral/clocker#137]
weave launch command fails as it can't connect to the other host and gets stuck:

```
Allocator range [169.254.0.0-169.255.0.0) awaiting consensus: Nodes known: 1, Quorum size: 2
Pending requests:
  Allocate for 64bb7a55698574e03bd3c5c6fe520dcaaf6a7a8a65f6939a06a5188d1793099e
Allocator default subnet: 169.254.0.0/16
```

**Comment by csabapalfi** [comment]
Could only reproduce it SL San Jose and when SL places my VMs in different VLAN (can also be seen by them being in a different /16 subnet). Probably clocker config for docker hosts need adjusting.

**Comment by csabapalfi** [comment]
Enabled (private) VLAN spanning in our Softlayer account and that fixed this.

@grkvlt Please re-open if you think we need to address this somehow in clocker.

**Comment by csabapalfi** [comment]
@grkvlt has a generic and more permanent fix to allow specifying VLAN ids.

**Comment by grkvlt** [comment]
I think we need the #138 fix because we want to deal with locations that may not be configured like ours, so I will merge my changes after testing some more

**Comment by csabapalfi** [comment]
Sure, my 'fix' is more of a workaround to allow demos and testing other stuff while your fix is merged.
