### ISSUE TITLE
Nodes in Calico cluster unable to communicate

### ISSUE THREAD

**Issue by sjcorbett** [brooklyncentral/clocker#152]
I ran Clocker version 1.1.0.PREVIEW_20150904 with Calico.

The cluster started ok (i.e. everything went green). I deployed the Riak web cluster example.  The Riak nodes are green but the "joinCluster" effector fails and the cluster entity is on fire.

The effector was executed in a container on a host in AWS with IP 54.177.12.78 and internal address 10.233.137.103. The container's addresses were ["50.0.1.4","50.0.2.4"]. 

Stdin:
```
( if test "$UID" -eq 0; then ( riak-admin cluster join riak@50.0.2.6 ); else sudo -E -n -S -- riak-admin cluster join riak@50.0.2.6; fi )
( if test "$UID" -eq 0; then ( riak-admin cluster plan ); else sudo -E -n -S -- riak-admin cluster plan; fi )
( if test "$UID" -eq 0; then ( riak-admin cluster commit ); else sudo -E -n -S -- riak-admin cluster commit; fi )
```

Stdout:
```
Node riak@50.0.2.6 is not reachable!
Executed /tmp/brooklyn-20150908-134159422-NSJ2-joinCluster_RiakNodeImpl_id_r2.sh, result 1
```

The container with address 50.0.2.6 is running in a host in AWS with IP 54.193.189.77. It has addresses ["50.0.2.6","50.0.1.5"].

The Docker hosts (in the same AWS availability zone) can ping each other. Neither container can ping the other on the 50.0.2.x or 50.0.1.x addresses.

**Comment by sjcorbett** [comment]
I'll add that each container can ping itself and Riak is happily running, albeit in three one-node clusters rather than one three-node cluster.

**Comment by grkvlt** [comment]
OK, this (should) be fixed now, with but I am building another release. There were two issues, one is fixed by adding IPIP support, the other was the version of Ubuntu, which is now autoselected based on the cloud. Will update @sjcorbett when another version is posted for testing.

**Comment by grkvlt** [comment]
See #161 - IPIP only works in VPCs on AWS, so closing.
