### ISSUE TITLE
Weave DelegateEntity continually shows STARTING (even though actual entity is running)

### ISSUE THREAD

**Issue by aledsage** [brooklyncentral/clocker#170]
Using master and also version 1.1.0-PREVIEW.20151005, I launched clocker+weave in AWS.

The weave01 `DelegateEntity` continued to report the attribute "ServiceState" as STARTING, even though the real weave01 entity had a ServiceState of RUNNING. The delegate entity therefore continued to be "spinning" green in the web-console, as though it was still starting up.

**Comment by grkvlt** [comment]
This looks like an issue with the `DelegateEntity` itself, perhaps?

**Comment by alasdairhodge** [comment]
Heads-up: now that apache/incubator-brooklyn#929 is merged, I'm looking into removing `DelegateEntity` (and other cruft in `AbstractGroup`) altogether.

**Comment by grkvlt** [comment]
@alasdairhodge agreed, but remember we'd need to be building Clocker against a SNAPSHOT branch of Brooklyn for that currently. I'd prefer to use fixed releases as dependencies in Clocker, although we could build a custom 0.9.0 release. @richardcloudsoft any idea when the 0.9.0 release is due?

**Comment by richardcloudsoft** [comment]
@grkvlt sorry I missed this comment. No discussion on the Apache Brooklyn release schedule / roadmap has happened on the list yet :disappointed:

**Comment by grkvlt** [comment]
Fixed
