### ISSUE TITLE
Skip Install

### ISSUE THREAD

**Issue by Graeme-Miller** [brooklyncentral/clocker#175]
When trying to replicate [issue 173](https://github.com/brooklyncentral/clocker/issues/173) I ran into an issue with a vanilla deployment of "Riak Cluster Demo Application" on AWS using Calico networking.

The application starts two tomcat servers. When provisioning a location from docker host for the first server, a dockerfile needs to be build. When the second is being provisioned, it checks for an image with the same ID, which succeeds due to the first server being provisioned already. Because this check succeeds we set SKIP_INSTALLATION to true on line 183 of DockerHostLocation.  

As the skip install has been set to true, tomcat is never installed in the container, and Tomcat cannot be started.

**Comment by grkvlt** [comment]
Needs further investigation. The image commit/pull mechanism works with other entities.

**Comment by grkvlt** [comment]
No repro, plus https://github.com/brooklyncentral/clocker/commit/9f34088d904bb0c155149c34cbaefb8acc092566 should fix this sort of thing
