### ISSUE TITLE
Error parsing tutorial YAML example

### ISSUE THREAD

**Issue by duncanjw** [brooklyncentral/clocker#179]
Hit a bug testing tutorial example 

https://gist.github.com/duncanjw/d07257384cf87c5062da

Cannot create spec for app: Transformer for Brooklyn OASIS CAMP interpreter gave an error creating this plan: java.lang.IllegalArgumentException: Error evaluating node '$brooklyn:sensor( "org.apache.brooklyn.entity.webapp.ControlledDynamicWebAppCluster", "webapp.reqs.perSec.windowed.perNode")'

First encountered with Version 1.1.0-PREVIEW.20151005 but reconfirmed with Version 1.1.0-PREVIEW.20151014.

Also reproduced when testing stock Brooklyn example -

http://brooklyn.incubator.apache.org/v/latest/yaml/clusters-and-policies.html using localhost

Cannot create spec for app: Transformer for Brooklyn OASIS CAMP interpreter gave an error creating this plan: java.lang.IllegalArgumentException: Error evaluating node '$brooklyn:sensor("brooklyn.entity.webapp.DynamicWebAppCluster", "webapp.reqs.perSec.windowed.perNode")'

(Arguably should be brooklyn.entity.webapp.ControlledDynamicWebAppCluster)

**Comment by grkvlt** [comment]
The underlying error is this: `Sensor webapp.reqs.perSec.windowed.perNode not found on class org.apache.brooklyn.entity.webapp.ControlledDynamicWebAppCluster`

Which is true, the `...windowed.perNode` sensor is on the `DynamicWebAppCluster` interface. If you replace the sensor definition with just `$brooklyn:sensor("webapp.reqs.perSec.windowed.perNode")` or change the class name to `DynamicWebAppCluster` this will work. The actual Brooklyn example needs to be changed though, outside of Clocker, I think.
