### ISSUE TITLE
Upgrade to Docker 1.9.x

### ISSUE THREAD

**Issue by grkvlt** [brooklyncentral/clocker#190]

**Comment by faddat** [comment]
In the meantime what version should I be using?  1.91 doesn't seem to happy at all:
https://gist.github.com/faddat/5eb75e13b6e830be2122

**Comment by Graeme-Miller** [comment]
@faddat I recently committed some code that allow versions of docker after 1.7 to be used- see [this commit](https://github.com/brooklyncentral/clocker/commit/b724e8398afb984af2549e90a060d62465f8d04e).

Was the error you were seeing using the most recent code from master?

**Comment by grkvlt** [comment]
Implemented in #286
