### ISSUE TITLE
Docker Cloud with Project Calico added in a STOPPED state

### ISSUE THREAD

**Issue by johnmccabe** [brooklyncentral/clocker#197]
Following the getting started instructions on http://clocker.io and starting clocker with:
```
./bin/clocker.sh softlayer-ams01 calico
```
Results in Clocker starting with the Docker Cloud in a STOPPED state, this does not appear to be intended as the instructions don't mention having to start via the Start Effector.
The cloud *does* start when you invoke the start effector.
Have tried with BYON and SL locations, and with the 1.1.0-PREVIEW.20151113 release and a local Brooklyn 0.9.0 based version.

**Comment by grkvlt** [comment]
@johnmccabe This may be because the `DockerInfrastructure` entity is of type `Application` now. @Graeme-Miller can you take a look, please?

**Comment by johnmccabe** [comment]
We've changed it to `StartableApplication` (was originally `BasicStartable`) and its starting as expected.

**Comment by grkvlt** [comment]
OK, will try that now. Do you mean just changing the interface extended by `DockerInfrastructure`?

**Comment by grkvlt** [comment]
Fixed by b34e5c364de8ab98e72ad0214e8b37624ec6f78f
