### ISSUE TITLE
Base image build fails in post-start task

### ISSUE THREAD

**Issue by sjcorbett** [brooklyncentral/clocker#216]
There's a timing issue in DockerHostImpl's postStart task that I only observe when deploying a host to the same region as Clocker and without SDN. I think `service docker status` (in the driver's isRunning method) outputs `running` before `docker.sock` is available for the API.

stdin of failing task:
```
sudo -E -n -S -- docker build --rm -t x15udmrnti /home/users/compose/brooklyn-managed-processes/apps/YJD9fhwc/entities/DockerHost_BllI9UgI/x15udmrnti
```

stderr:
```
Post http:///var/run/docker.sock/v1.19/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=x15udmrnti: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```

If I force Clocker to wait a few seconds immediately before attempting to build the image the task succeeds.

Is it worth altering `isRunning` to check that the API is available too?

**Comment by grkvlt** [comment]
Yes, although I hate solutions like that :crying_cat_face:

**Comment by Graeme-Miller** [comment]
Fixed by:
https://github.com/brooklyncentral/clocker/pull/220
