### ISSUE TITLE
Cannot run privileged containers

### ISSUE THREAD

**Issue by sjcorbett** [brooklyncentral/clocker#221]
I'd like to indicate that a container should be [privileged](https://docs.docker.com/engine/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration). `DockerContainer` has a `PRIVILEGED` config key but it is never used. I think `DockerTemplateOptions` may also need to be updated.

**Comment by grkvlt** [comment]
@sjcorbett the jclouds API actually always sets this, in [DockerComputeServiceAdapter](https://github.com/jclouds/jclouds-labs/blob/master/docker/src/main/java/org/jclouds/docker/compute/strategy/DockerComputeServiceAdapter.java#L122). I added the config key before I realised this. @andreaturli could we make this a setting in `DockerTemplateOptions` instead?

**Comment by grkvlt** [comment]
Added proper support for privileged option in #286
