### ISSUE TITLE
Fix mapped.main.uri

### ISSUE THREAD

**Issue by Graeme-Miller** [brooklyncentral/clocker#231]
Clocker UI currently displays the wrong URI on the Summary page for an entity.
It displays main.uri, but should display mapped.main.uri

**Comment by grkvlt** [comment]
Should check for presence of mapped URI in the JS code for the summary pane.

**Comment by grkvlt** [comment]
Fixed in https://github.com/brooklyncentral/clocker/commit/0ee83fd42581eb73c1255e48f6a06c2263b754e5
