### ISSUE TITLE
Clocker Caching

### ISSUE THREAD

**Issue by Graeme-Miller** [brooklyncentral/clocker#245]
Clocker currently attempts to re-use images for entities.
If it detects an image, it goes directly to customize and then launch.

This has caused issue where certain entities (Tomcat, MariaDB, Nginx) cannot be used more than once on a docker infrastructure.

We should consider disabling this behaviour, or fixing the re-use issue and adding config to disable image caching.

**Comment by andreaturli** [comment]
+1, thanks @Graeme-Miller for tracking the issue

**Comment by grkvlt** [comment]
Fixed by https://github.com/apache/brooklyn-server/pull/37 and https://github.com/apache/brooklyn-library/pull/14

**Comment by grkvlt** [comment]
Should create a separate issue for adding a configuration option to disable, on a per-entity/application basis
