### ISSUE TITLE
docker fails to install on ubuntu vivid 15.04

### ISSUE THREAD

**Issue by johnmccabe** [brooklyncentral/clocker#284]
Fails during `ssh: installing DockerHostImpl`, location didn't have os locked down to the LTS release trusty 14.04
```
E: Version '1.10.3-0~vivid' for 'docker-engine' was not found
WARNING: no known/successful package manager to install docker-engine=1.10.3-0~vivid, may fail subsequently
```
Should we expect this to work on 15.04? or is it trusty + wily only?

**Comment by johnmccabe** [comment]
this was using the default template (works find with `1.9.1`), unable to specify an Ubuntu 15.10 image currently (looks like a separate issue).

**Comment by grkvlt** [comment]
OK, looks like 15.04 doesn't have the latest Docker in its repos. We need to validate the different OS and Docker version combos, I guess.

**Comment by johnmccabe** [comment]
This was Blue Box Openstack.

**Comment by grkvlt** [comment]
This should be raised with them as a support issue.

**Comment by grkvlt** [comment]
Docker does not support the Ubuntu 15.04 repos, so have changed the default to 15.10 now.
