### ISSUE TITLE
1.1.0 clocker release breaks AWS docker weave cloud.

### ISSUE THREAD

**Issue by avedz** [brooklyncentral/clocker#294]
When a new docker image is creating in a weave docker cloud this error appears:
No such plugin error

**Comment by grkvlt** [comment]
@avedz thanks for the report. I'll check if we have the right plugin details for libnetwork and weave. I thought I had changed them. Look out for a 1.1.1 release with this fixed, shortly.

**Comment by grkvlt** [comment]
@avedz This is now fixed in master by #296
