### ISSUE TITLE
command line args aren't passed through to brooklyn.sh

### ISSUE THREAD

**Issue by johnmccabe** [brooklyncentral/clocker#297]
Attempting to start clocker on the command line with brooklyn persistence args fails, there is a `${PERSISTENCE_FLAGS}` envvar passed through to brooklyn but not populated by the `clocker.sh` script.

```
# ./bin/clocker.sh --persist auto
Cannot find blueprint for network auto
Supported network options: weave, calico, host, localhost
```

**Comment by grkvlt** [comment]
See the `./bin/persist.sh` script for an example of `PERSISTENCE_FLAGS` variable usage

**Comment by johnmccabe** [comment]
Ah, thanks @grkvlt, I'd just been setting the var in my local env when starting `clocker.sh`.
