### ISSUE TITLE
BOM syntax not supported in Brooklyn 0.9.0?

### ISSUE THREAD

**Issue by tjwebb** [brooklyncentral/clocker#373]
When I paste the clocker bom into the Brooklyn composer, I get this:

```
 Expected map for entry in items list, not string
```

I'm pasting this:

```
brooklyn.catalog:
  items:
    - classpath://swarm/catalog.bom
    - classpath://kubernetes/catalog.bom
```

**Comment by neykov** [comment]
@tjwebb The include syntax you are using is not supported in Brooklyn 0.9.0. That's the reason the [getting started](http://www.clocker.io/tutorials/getting-started.html) tutorial links to a master build of Brooklyn which has all the needed features for the swam & kubernetes blueprints to work.

The good news is that a 0.10.0 release of Apache Brooklyn is on the [horizon](https://mail-archives.apache.org/mod_mbox/brooklyn-dev/201611.mbox/%3C610b640c-977c-7a0b-4e17-1f5f8adbb475%40gmail.com%3E) so you'll be able to use the blueprints with it out of the box.

Closing this. Please feel free to re-open if you need more information.
