### ISSUE TITLE
Clocker trying to stop already stopped docker daemon

### ISSUE THREAD

**Issue by ondrej-smola** [brooklyncentral/clocker#80]
I have 2 machines (using byon, trusty, docker 1.2) - when i create clocker cloud from scratch (both machines running docker daemon) everything works. Removing clocker cloud stops docker daemons. 
Attempt to create clocker cloud again fails on stopping already stopped docker daemons. 

From logs i suspect dockerhost status check returns 0 (docker stop/waiting in output) - it triggers dockerhost stop script execution failing with 1 exit status code.

![clocker](https://cloud.githubusercontent.com/assets/851390/5450650/d63e606c-8508-11e4-98d2-c70cd844f76f.png)

**Comment by sjcorbett** [comment]
I think this should have been fixed in #90.

**Comment by grkvlt** [comment]
@sjcorbett Agree
